services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: pipos_fitness
    ports:
      - "5432:5432"
    volumes:
      - pipos_db:/var/lib/postgresql/data
volumes:
  pipos_db:
